### ISSUE TITLE
FileNotFound Error

### ISSUE THREAD

**Issue by Scrooge20291224** [jaymz07/ray-tracer#1]
FileNotFoundError: [Errno 2] No such file or directory: 'cateyeDelayStage.pkl'

**Comment by nuggetofwisdom** [comment]
Did you ever solve this?

**Comment by Scrooge20291224** [comment]
> Did you ever solve this?

Just delete that line.

**Comment by jaymz07** [comment]
That was to load a pickle file containing a configuration I was using as a demo.
The top lines of the program give the initial optical configuration, and that pickle file was just simplifying the setup procedure.
The newest push should work without trying to find this file.

Happy tracing haha ^_^
